#!/usr/bin/env bash
### .aliases - spend less time typing

# load private, non-tracked, aliases
if [ -f ~/.aliases_priv ]; then
  source ~/.aliases_priv
fi

# shell commands
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias clr="clear"
alias cls="clear"
alias grep='$(which grep) --color=always'
alias home="cd ~"
alias play="afplay"
alias rebash="source ~/.bashrc"
alias rmd='rm -rf'
alias sizeof="du -sh"
alias untar="tar -xvf"

# mac-specific directory shortcuts
alias db="cd ~/Dropbox"
alias dl="cd ~/Downloads"
alias sites="cd ~/Sites"

# mac-specific commands
alias backup="tmutil startbackup"

# symfony
alias sf="symfony"
alias sfstart="php bin/console server:start"
alias sfstop="php bin/console server:stop"
alias sfup="symfony self-update"

# git
alias gitlog="git lg -20"
alias sgit='git branch -a | grep'

# package management
alias brewup="brew update && brew upgrade && brew cleanup"
alias gemup="gem update --system && gem update && gem cleanup"
alias gemups="gem update --system"

# ruby
alias be="bundle exec"

# docker
alias dc="docker-compose"
alias dm="docker-machine"
alias ds='docker exec -it -e COLUMNS=$COLUMNS'
alias dockers="cd ~/Dockers"

# hugo
alias hugos="hugo serve --disableFastRender"

# miscellaneous
HTTP_SERVICES="httpd\|vpnkit\|java\|nc\|node\|ng\|php\|ruby\|hugo\|docker\|com.docker\|com.docke"

alias dandeploy="dandelion deploy"
alias gcal=gcalcli
alias httports='lsof -i -n -P | grep $HTTP_SERVICES | grep LISTEN | egrep -o ":[0-9]{2,5}" | cut -f2- -d: | sort -n | uniq'
alias httportss='sudo lsof -i -n -P | grep $HTTP_SERVICES | grep LISTEN | egrep -o ":[0-9]{2,5}" | cut -f2- -d: | sort -n | uniq'
alias myip="curl icanhazip.com"
alias repostfix="sudo launchctl stop org.postfix.master; sudo launchctl start org.postfix.master"
alias sqlite="sqlite3"
alias ytdl="youtube-dl -t"
alias ytdla="youtube-dl --extract-audio --audio-format mp3"
