#!/usr/bin/env bash
### .aliases - spend less time typing

# load private, non-tracked, aliases
if [ -f ~/.aliases_priv ]; then
  source ~/.aliases_priv
fi

# shell commands
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias clr="clear"
alias cls="clear"
alias edit=$EDITOR
alias grep="`which grep` --color=always"
alias home="cd ~"
alias modify=$EDITOR
alias play="afplay"
alias rebash="source ~/.bashrc"
alias reweb="sudo apachectl -k restart"
alias rmd="rm -rf $1"
alias sizeof="du -sh $1"
alias tailhttp="tail -f $1 | awk '/[5[0-9][0-9]|4[0-9][0-9]]/ {print \"\033[31m\" $0 \"\033[39m\"} /3[0-9][0-9] {print \"\033[33m\" $0 \"\033[39m\"} /20[0-9]/ {print
\"\033[32m\" $0 \"\033[39m\"} /[1[0-9][0-9]|[6-9][0-9][0-9]])/ {print \"\033[37m\" $0 \"\033[39m\"}'"
alias untar="tar -xvf $1"

# mac-specific directory shortcuts
alias apps="cd /Applications"
alias db="cd ~/Dropbox"
alias dl="cd ~/Downloads"
alias docs="cd ~/Documents"
alias sites="cd ~/Sites"

# mac-specific commands
alias backup="tmutil startbackup"

# php
alias composer="php /usr/local/bin/composer.phar"
alias compup="composer selfupdate"
# symfony
alias sf="symfony"
alias sfstart="php bin/console server:start"
alias sfstop="php bin/console server:stop"
alias sfup="symfony self-update"

# react
alias crna="create-react-native-app $1"

# git
alias gitlog="git lg -20"
alias sgit="git branch -a | grep $1"

# package management
alias brewup="brew update && brew upgrade && brew cleanup"
alias gemup="gem update && gem cleanup"
alias gemups="gem update --system"

# ruby
alias be="bundle exec"

# docker
alias dc="docker-compose"
alias dm="docker-machine"
alias ds="docker exec -it $1 $2"
alias dockers="cd ~/Dockers"

# miscellaneous
alias dandeploy="dandelion deploy"
alias gcal=gcalcli
alias httports="lsof -i -n -P | grep 'httpd\|vpnkit\|java\|nc\|node\|ng\|php' | grep LISTEN | egrep -o ':[0-9]{2,5}' | cut -f2- -d: | sort -n | uniq"
alias httportss="sudo lsof -i -n -P | grep 'httpd\|vpnkit\|java\|nc\|node\|ng\|php' | grep LISTEN | egrep -o ':[0-9]{2,5}' | cut -f2- -d: | sort -n | uniq"
alias httprocs="lsof -i -n -P | grep 'httpd\|vpnkit\|java\|nc\|node\|ng' | grep LISTEN | awk '{print \$1}' | sort -n"
alias httprocss="sudo lsof -i -n -P | grep 'httpd\|vpnkit\|java\|nc\|node\|ng' | grep LISTEN | awk '{print \$1}' | sort -n | uniq"
alias myip="curl -s ip.appspot.com"
alias repostfix="sudo launchctl stop org.postfix.master; sudo launchctl start org.postfix.master"
alias sqlite="sqlite3"
alias ytdl="youtube-dl -t"
alias ytdla="youtube-dl --extract-audio --audio-format mp3"
