#!/usr/bin/env bash

# load aliases
if [ -f ~/.aliases ]; then
  source ~/.aliases
fi

# load main functions file
if [ -f ~/.functions ]; then
  source ~/.functions
fi

# load local (private) settings
if [ -f ~/.localrc ]; then
  source ~/.localrc
fi

# load lita settings
if [ -f ~/.litarc ]; then
  source ~/.litarc
fi

# load random scripts
if [ -d ~/.scripts ]; then
  for f in ~/.scripts/*.sh; do
    source $f
  done
  # additional function-scoped scripts
  source ~/.scripts/_others/goto
  if [ -f ~/.gotorc ]; then
    source ~/.gotorc >/dev/null 2>&1
  fi
fi

# bash completion
[ -f /usr/local/etc/bash_completion ] && . /usr/local/etc/bash_completion

# rust/cargo
source $HOME/.cargo/env

# drupal
source "$HOME/.console/console.rc" 2>/dev/null

# misc settings
export TXTAPP=vi
export COLORIZE=1
export CLICOLOR=1
export LSCOLORS=gxBxhxDxfxhxhxhxhxcxcx
export EDITOR=$TXTAPP
export GEMEDITOR=$TXTAPP
export PROMPT_COMMAND="printf '\e]0;bash\7'" # fix title bar post-ssh
export HISTTIMEFORMAT='%F %T %t'

# go
export GOPATH="$DROPBOX_HOME/code/go"
export GOROOT="/usr/local/opt/go/libexec"
export GOBIN="$GOPATH/bin"

# git
export GIT_PS1_SHOWDIRTYSTATE=1
source ~/.git-prompt.sh

# node
export NODE_PATH="$HOME/.npm"

# rbenv
eval "$(rbenv init -)"

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# load custom path
if [ -f ~/.pathrc ]; then
  source ~/.pathrc
fi

# load custom prompt
if [ -f ~/.promptrc ]; then
  source ~/.promptrc
fi
