#!/usr/bin/env bash

# load aliases
source ~/.aliases

# symlink ~/code to db, if it doesn't exist
if [ ! -e ~/Code ]; then
  ln -s ~/Dropbox/Code ~/Code
fi

# mkdir and cd
_md() {
  mkdir $1 && eval cd $1;
}

# local vars for prompt colors
e=`printf "\033"`
end="$e[0m"
red="$e[1;31m"
green="$e[1;32m"
yellow="$e[1;33m"
blue="$e[1;34m"
magenta="$e[1;35m"
darkcyan="$e[36m"

# path
export PATH=.bundle/bin:/usr/local/heroku/bin:/Users/mike/.rbenv/shims:/usr/local/bin:/usr/local/sbin:/usr/local/mysql/bin:/usr/lib/cake/console:/usr/local/git/bin:/Developer/usr/bin:$PATH

# misc settings
export COLORIZE=1
export CLICOLOR=1
export EDITOR="/usr/bin/nano"
export GEMEDITOR="/usr/bin/mate"

# rbenv
source "/usr/local/Cellar/rbenv/0.3.0/libexec/../completions/rbenv.bash"
rbenv rehash 2>/dev/null
rbenv() {
  command="$1"
  if [ "$#" -gt 0 ]; then
    shift
  fi

  case "$command" in
  shell)
    eval `rbenv "sh-$command" "$@"`;;
  *)
    command rbenv "$command" "$@";;
  esac
}

# git
alias git=hub
_parse_git_branch() {
  ref=$(git symbolic-ref HEAD 2> /dev/null) || return
  echo "("${ref#refs/heads/}")"
}

# cakephp
alias icp="/usr/lib/cake/console/cake"

# Local (private) settings
if [ -f ~/.localrc ]; then
  source ~/.localrc
fi

# prompt
export PS1="\[${red}\][\w]\[${darkcyan}\]\$(_parse_git_branch)\n\[${green}\]\u@\h\[${yellow}\](\$(date +%T))\[${end}\]$ "

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"
