#!/usr/bin/env bash

# load aliases
if [ -f ~/.aliases ]; then
  source ~/.aliases
fi

# load functions
if [ -f ~/.functions ]; then
  source ~/.functions
fi

# load local (private) settings
if [ -f ~/.localrc ]; then
  source ~/.localrc
fi

# load lita settings
if [ -f ~/.litarc ]; then
  source ~/.litarc
fi

# bash completion
[ -f /usr/local/etc/bash_completion ] && . /usr/local/etc/bash_completion

# load rust/cargo
source $HOME/.cargo/env

# load drupal settings
source "$HOME/.console/console.rc" 2>/dev/null

# local vars for prompt colors
e=`printf "\033"`
end="$e[0m"
red="$e[1;31m"
green="$e[1;32m"
yellow="$e[1;33m"
blue="$e[1;34m"
magenta="$e[1;35m"
cyan="$e[36m"

# misc settings
export TXTAPP=nano
export COLORIZE=1
export CLICOLOR=1
export LSCOLORS=gxBxhxDxfxhxhxhxhxcxcx
export EDITOR=$TXTAPP
export GEMEDITOR=$TXTAPP
export PROMPT_COMMAND="printf '\e]0;bash\7'" # fix title bar post-ssh
export HISTTIMEFORMAT='%F %T %t'

# go
export GOPATH="$DROPBOX_HOME/code/go"
export GOROOT="/usr/local/opt/go/libexec"
export GOBIN="$GOPATH/bin"

# git
export GIT_PS1_SHOWDIRTYSTATE=1
source ~/.git-prompt.sh

# rbenv
eval "$(rbenv init -)"

# path
PATH=.bundle/bin:$PATH
PATH=$HOME/.composer/vendor/bin:$PATH
PATH=$HOME/.rbenv/shims:$PATH
PATH=$HOME/.scripts:$PATH
PATH=$HOME/.scripts/_others:$PATH
PATH=/Library/Developer/Toolchains/swift-latest.xctoolchain/usr/bin:$PATH
PATH=/usr/local/git/bin:$PATH
PATH=/usr/local/heroku/bin:$PATH
PATH=/usr/local/mysql/bin:$PATH
PATH=/usr/local/bin:$PATH
PATH=/usr/local/sbin:$PATH
PATH=/usr/sbin:$PATH
PATH=/usr/lib/cake/console:$PATH
PATH=$GOBIN:$PATH
PATH=$GOROOT:$PATH
PATH=/Developer/usr/bin:$PATH
PATH=$PATH:$HOME/bin

export PATH

# prompt
export PS1="\[${red}\][\w]\[${cyan}\]\$(__git_ps1)\n"
export PS1="$PS1\[${green}\]\u\[${yellow}\]@\[${green}\]\h\[${yellow}\](\$(date +%T))\[${end}\] "

export PATH="$PATH:/Applications/DevDesktop/tools"

