#!/usr/bin/env bash
### .exports - public global env vars
# shellcheck source=/dev/null

# misc
export BASH_SILENCE_DEPRECATION_WARNING=1
export CLICOLOR=1
export COLORIZE=1
export COMPOSE_HTTP_TIMEOUT=300 # docker-compose increase timeout
export EDITOR=$TXTAPP
export GEMEDITOR=$TXTAPP
export HTTP_SERVICES="httpd\|vpnkit\|java\|nc\|node\|ng\|php\|ruby\|hugo\|docker\|com.docker\|com.docke"
export LSCOLORS=gxBxhxDxfxhxhxhxhxcxcx
export PROMPT_COMMAND='printf "\e]0;bash\7"' # fix prompt post-ssh
export STARSHIP_CONFIG=$HOME/.starship/config.toml
export TXTAPP=vi

# bash history
export HISTCONTROL=ignoreboth
export HISTFILESIZE=2000
export HISTSIZE=1000
export HISTTIMEFORMAT='%F %T %t'

# crystal
export CRYSTAL_OPTS="--link-flags=-Wl,-ld_classic"

# go
export GOPATH="$CODE/go"
export GOBIN="$GOPATH/bin"
export GOROOT="/usr/local/opt/go/libexec"

# git
export GIT_PS1_SHOWCOLORHINTS=1
export GIT_PS1_SHOWDIRTYSTATE=1
export GIT_PS1_SHOWSTASHSTATE=1
export GIT_PS1_SHOWUNTRACKEDFILES=1
export GIT_PS1_SHOWUPSTREAM="verbose name"

# node
export NODE_PATH="$HOME/.npm"
export NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules
export NODE_OPTIONS="--dns-result-order=ipv4first"

##########################################################

# load private, non-tracked, exports
if [ -f "$HOME"/.exports_priv ]; then source "$HOME"/.exports_priv; fi
