#!/usr/bin/env bash
### .exports - global env vars

# load private, non-tracked, exports
if [ -f ~/.exports_priv ]; then
  source ~/.exports_priv
fi

export DROPBOX_HOME="$HOME/Dropbox"
export HTTP_SERVICES="httpd\|vpnkit\|java\|nc\|node\|ng\|php\|ruby\|hugo\|docker\|com.docker\|com.docke"

export TXTAPP=vi
export COLORIZE=1
export CLICOLOR=1
export LSCOLORS=gxBxhxDxfxhxhxhxhxcxcx
export EDITOR=$TXTAPP
export GEMEDITOR=$TXTAPP
export PROMPT_COMMAND='printf "\e]0;bash\7"' # fix prompt post-ssh
export HISTTIMEFORMAT='%F %T %t'
export COMPOSE_HTTP_TIMEOUT=300 # docker-compose increase timeout

# go
export GOPATH="$DROPBOX_HOME/code/go"
export GOROOT="/usr/local/opt/go/libexec"
export GOBIN="$GOPATH/bin"

# git
export GIT_PS1_SHOWDIRTYSTATE=1
export GIT_PS1_SHOWSTASHSTATE=1
export GIT_PS1_SHOWUNTRACKEDFILES=1
export GIT_PS1_SHOWUPSTREAM="verbose name"
export GIT_PS1_SHOWCOLORHINTS=1

# node
export NODE_PATH="$HOME/.npm"
export NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules
export NVM_DIR="$HOME/.nvm"
