#!/usr/bin/env bash
### .functions_iterm - functions specific to iterm

# change tab color
function tab-color {
  case $1 in
    green)
    echo -n -e "\033]6;1;bg;red;brightness;57\a"
    echo -n -e "\033]6;1;bg;green;brightness;197\a"
    echo -n -e "\033]6;1;bg;blue;brightness;77\a"
    ;;
    red)
    echo -n -e "\033]6;1;bg;red;brightness;270\a"
    echo -n -e "\033]6;1;bg;green;brightness;60\a"
    echo -n -e "\033]6;1;bg;blue;brightness;83\a"
    ;;
    orange)
    echo -n -e "\033]6;1;bg;red;brightness;227\a"
    echo -n -e "\033]6;1;bg;green;brightness;143\a"
    echo -n -e "\033]6;1;bg;blue;brightness;10\a"
    ;;
    blue)
    echo -n -e "\033]6;1;bg;red;brightness;30\a"
    echo -n -e "\033]6;1;bg;green;brightness;144\a"
    echo -n -e "\033]6;1;bg;blue;brightness;255\a"
    ;;
    purple)
    echo -n -e "\033]6;1;bg;red;brightness;147\a"
    echo -n -e "\033]6;1;bg;green;brightness;112\a"
    echo -n -e "\033]6;1;bg;blue;brightness;219\a"
    ;;
    yellow)
    echo -n -e "\033]6;1;bg;red;brightness;255\a"
    echo -n -e "\033]6;1;bg;green;brightness;255\a"
    echo -n -e "\033]6;1;bg;blue;brightness;0\a"
    ;;
    reset)
    echo -n -e "\033]6;1;bg;red;brightness;255\a"
    echo -n -e "\033]6;1;bg;green;brightness;255\a"
    echo -n -e "\033]6;1;bg;blue;brightness;255\a"
    ;;
  esac
}
# change bg color
function bg-color {
  local R=$1
  local G=$2
  local B=$3
  /usr/bin/osascript <<EOF
	tell application "iTerm2"
	  tell the current window
      tell the current session
	      set background color to {$(echo "scale=2; ($1/255.0)*65535" | bc),$(echo "scale=2; ($2/255.0)*65535" | bc),$(echo "scale=2; ($3/255.0)*65535" | bc)}
      end tell
	  end tell
	end tell
EOF
}

# color ssh session tabs and backgrounds
function color-ssh {
  if [[ "$@" =~ sioatomic-dev ]]; then
    tab-color green
    bg-color 0 60 2
  elif [[ "$@" =~ sioatomic-stage ]]; then
    tab-color blue
    bg-color 0 12 59
  elif [[ "$@" =~ sioatomic ]]; then
    tab-color red
    bg-color 59 7 0
  fi

  ssh "$@"
  tab-color reset
  bg-color 0 0 0
}
alias ssh=color-ssh

# set window/tab namee
function set_iterm_name {
  mode=$1; shift
  echo -ne "\033]$mode;$@\007"
}

function set_term_random_bgcolor {
	set_term_bgcolor $(echo $(echo 0."$RANDOM")*255 | bc) $(echo $(echo 0."$RANDOM")*255 | bc) $(echo $(echo 0."$RANDOM")*255 | bc)
}
function iterm_both { set_iterm_name 0 "$@"; }
function iterm_tab { set_iterm_name 1 "$@"; }
function iterm_window { set_iterm_name 2 "$@"; }
