#!/usr/bin/env bash
### .functions_fun - more complicated aliases, for fun

function fun() {
  if [ $# -eq 0 ]; then
    echo "Wasn't that fun? Maybe add 'snow' or some other word next time."
  fi

  while [[ $# -gt 0 ]]
  do
  key="$1"
    case $key in
      colors)
      # color show in your terminal
      # source: https://twitter.com/climagic/status/817405740772184065
      yes "$(seq 16 231)" | while read i;
      do printf "\x1b[48;5;${i}m\n";
      sleep .02;
      done
      ;;
      snow)
      # make it snow in your terminal
      # source: http://climagic.org/coolstuff/let-it-snow.html
      export LINES COLUMNS;
      clear;
      while :;
      do echo $LINES $COLUMNS $(($RANDOM%$COLUMNS));
      sleep 0.1;
      done|gawk '{a[$3]=0;for(x in a) {o=a[x];a[x]=a[x]+1;printf "\033[%s;%sH ",o,x; printf "\033[%s;%sH*\033[0;0H",a[x],x;}}'
      ;;
    esac
    shift
  done
}


