#!/usr/bin/env bash
### .pathrc - custom command path

# path
DEFAULT_PATH=$HOME/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

PATH=$DEFAULT_PATH
PATH=/usr/local/sbin:$PATH
PATH=.bundle/bin:$PATH
PATH=$HOME/.composer/vendor/bin:$PATH
PATH=$HOME/.rbenv/shims:$PATH
PATH=$HOME/.scripts:$PATH
PATH=$HOME/.scripts/_others:$PATH
PATH=/Library/Developer/Toolchains/swift-latest.xctoolchain/usr/bin:$PATH
PATH=/usr/local/git/bin:$PATH
PATH=/usr/local/heroku/bin:$PATH
PATH=/usr/local/mysql/bin:$PATH
PATH=/usr/lib/cake/console:$PATH
PATH=$GOBIN:$PATH
PATH=$GOROOT:$PATH
PATH=/Developer/usr/bin:$PATH
PATH=/opt/X11/bin:$PATH
PATH=/usr/local/MacGPG2/bin:$PATH
PATH=/Library/Frameworks/Mono.framework/Versions/Current/Commands:$PATH
PATH=/usr/local/munki:$PATH
PATH=/usr/local/opt/imagemagick@6/bin:$PATH
PATH=$HOME/.cargo/bin:$PATH
PATH=$HOME/Library/Python/2.7/bin:$PATH
PATH=$HOME/Library/Python/3.7/bin:$PATH

export PATH
