#!/usr/bin/env bash
### .promptrc - custom command prompt

# local vars for prompt colors
_RESET="$(tput sgr0)"
# fg colors
#_BLACK_FG="$(tput setaf 0)"
#_RED_FG="$(tput setaf 1)"
_GREEN_FG="$(tput setaf 2)"
_YELLOW_FG="$(tput setaf 3)"
#_PURPLE_FG="$(tput setaf 4)"
#_MAGENTA_FG="$(tput setaf 5)"
#_DARKCYAN_FG="$(tput setaf 6)"
#_WHITE_FG="$(tput setaf 7)"
_BRIGHTCYAN_FG="$(tput setaf 14)"
_BOLD="$(tput bold)"

_ddev_pst1() {
  if [ -f ".ddev/config.yaml" ]; then
    # if [ "$(ddev st)" ]; then
    #   echo "${_YELLOW_FG}${_BOLD} [ddev-on]${_RESET}"
    # else
    #   echo "${_YELLOW_FG} [ddev-off]${_RESET}"
    # fi
    echo "${_YELLOW_FG} [ddev]${_RESET}"
  fi
}
# prompt vars
PS1_DIR="${_GREEN_FG}[\w]${_RESET}"
PS1_GIT="${_BRIGHTCYAN_FG}${_BOLD}\$(__git_ps1)${_RESET}"
PS1_DDEV="\$(_ddev_pst1)"
PS1_USER="\[${_GREEN_FG}${_BOLD}\]\u\[${_YELLOW_FG}${_BOLD}\]@\[${_GREEN_FG}${_BOLD}\]\h\[${_RESET}\]"
PS1_DATE="\[${_YELLOW_FG}${_BOLD}\](\$(date +%T))\[${_RESET}\]"

# [dir] [ddev] (git)
export PS1_CUSTOM1="$PS1_DIR$PS1_DDEV$PS1_GIT\n"

# adding emoji via emo
# if [ -f $GOPATH/bin/emo ]; then
#  export PS1_CUSTOM1="$($GOPATH/bin/emo -n house-building) $PS1_CUSTOM1"
# fi

# user(date) $
export PS1_CUSTOM1="$PS1_CUSTOM1$PS1_USER$PS1_DATE "

# save prompt
export PS1=$PS1_CUSTOM1
