#!/usr/bin/env bash
### .promptrc - custom command prompt

# local vars for prompt colors
e=`printf "\033"`
end="$e[0m"
# black="$e[1;30m"
red="$e[1;31m"
green="$e[1;32m"
yellow="$e[1;33m"
# blue="$e[1;34m"
# magenta="$e[1;35m"
cyan="$e[1;36m"
# white="$e[1;97m"
# red_bg="$e[0;41m"

# prompt
PS1_USER="\[${green}\]\u\[${yellow}\]@\[${green}\]\h\[${end}\]"
PS1_DATE="\[${yellow}\](\$(date +%T))\[${end}\]"
#PS1_GIT="\[${cyan}\]\$(__git_ps1)\[${end}\]"
PS1_GIT="\$(__git_ps1)"
PS1_DIR="\[${red}\][\w]\[${end}\]"

# user(date) (git)
# [dir] $
export PS1_CUSTOM1="$PS1_USER$PS1_DATE$PS1_GIT\n"
export PS1_CUSTOM1="$PS1_CUSTOM1$PS1_DIR "

# [dir] (git)
# user(date) $
export PS1_CUSTOM2="\[${red}\][\w]\[${end}\]\[${cyan}\]\$(__git_ps1)\n"
#export PS1_CUSTOM2="\[${red}\][\w]\[${end}\]\$(__git_ps1)\n"
# adding emoji via emo
if [ -f $GOPATH/bin/emo ]; then
  export PS1_CUSTOM2="$PS1_CUSTOM2$($GOPATH/bin/emo -n house-building) "
fi
export PS1_CUSTOM2="$PS1_CUSTOM2\[${green}\]\u\[${yellow}\]@\[${green}\]\h\[${yellow}\](\$(date +%T))\[${end}\] "

export PS1=$PS1_CUSTOM2
