#!/usr/bin/env bash
### .sshrc - commands to be available when sshing

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias clr='clear'
alias cls='clear'
alias rebash='source $HOME/.bashrc'
